const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const {normalizeEvent,normalizeStore,DEFAULT_SETTINGS,reminderCandidates,attention,daysUntil,smartSort,progress,sampleEvents}=require('../app/domain.cjs');
const {Store}=require('../app/store.cjs');
const now=new Date('2026-10-05T12:00:00');
const make=overrides=>normalizeEvent({title:'测试事项',...overrides},now.toISOString());
const data=events=>({version:1,settings:{...DEFAULT_SETTINGS},events,notificationHistory:{}});
test('截止和跟进时间独立；没有 DDL 的事项仍可提醒',()=>{const e=make({followUp:'2026-10-05T09:00',deadline:''});const candidates=reminderCandidates(data([e]),now);assert.equal(candidates.length,1);assert.equal(candidates[0].eventId,e.id);assert.equal(attention(e,now).kind,'follow');});
test('已完成、回收站和稍后提醒中的事项不会触发通知',()=>{for(const overrides of [{status:'completed'},{deletedAt:'2026-10-05T10:00'},{snoozeUntil:'2026-10-05T13:00'}])assert.equal(reminderCandidates(data([make({followUp:'2026-10-05T09:00',...overrides})]),now).length,0);});
test('提醒只发一次；修改跟进时间会生成新的提醒',()=>{const e=make({followUp:'2026-10-05T09:00'}),store=data([e]);const first=reminderCandidates(store,now)[0];store.notificationHistory[first.key]=now.toISOString();assert.equal(reminderCandidates(store,now).length,0);e.followUp='2026-10-05T10:00';assert.equal(reminderCandidates(store,now).length,1);});
test('没有 DDL 和跟进时间的事项也可以稍后提醒',()=>{const e=make({snoozeUntil:'2026-10-05T11:00'}),store=data([e]);const reminder=reminderCandidates(store,now);assert.equal(reminder.length,1);assert.ok(reminder[0].key.startsWith('snooze:'));store.notificationHistory[reminder[0].key]=now.toISOString();assert.equal(reminderCandidates(store,now).length,0);});
test('提前提醒从当地日历的上午九点开始',()=>{const e=make({deadline:'2026-10-08'}),store=data([e]);assert.equal(reminderCandidates(store,new Date('2026-10-05T08:59')).length,0);assert.equal(reminderCandidates(store,new Date('2026-10-05T09:00')).length,1);});
test('当天超过指定截止时刻时已经逾期',()=>{const e=make({deadline:'2026-10-05',deadlineTime:'11:00'});assert.equal(attention(e,now).kind,'overdue');assert.ok(reminderCandidates(data([e]),now)[0].key.startsWith('overdue:'));});
test('剩余天数按日历计算，不因一天的具体时刻变化',()=>{assert.equal(daysUntil('2026-10-08',new Date('2026-10-05T23:59')),3);assert.equal(daysUntil('2026-10-05',now),0);});
test('逾期和需要跟进的事项排在其他事项之前',()=>{const ordinary=make({title:'普通',priority:'high'}),follow=make({title:'跟进',followUp:'2026-10-05T09:00'}),late=make({title:'逾期',deadline:'2026-10-04'});assert.deepEqual(smartSort([ordinary,follow,late],now).map(e=>e.title),['逾期','跟进','普通']);});
test('备份校验拒绝错误格式、无效日期和重复编号',()=>{assert.throws(()=>normalizeStore({events:[]}));assert.throws(()=>make({deadline:'2026-02-30'}));assert.throws(()=>make({followUp:'2026-02-30T09:00'}));const e=make({});assert.throws(()=>normalizeStore(data([e,e])));});
test('阶段进度和示例标记可以保存并重新读取',()=>{const e=make({demo:true,steps:[{title:'第一步',done:true},{title:'第二步',done:false}]});const restored=normalizeStore(data([e])).events[0];assert.equal(restored.demo,true);assert.deepEqual(progress(restored),{done:1,total:2,percent:50});assert.equal(sampleEvents(now).length,6);});
test('数据重开仍然存在；自动备份保留原来的完整内容',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'xevent-test-'));try{const store=new Store(dir),first=make({title:'第一次保存'});store.data.events.push(first);store.save();store.data.events[0].title='第二次保存';store.save();const reopened=new Store(dir);assert.equal(reopened.data.events[0].title,'第二次保存');const backups=fs.readdirSync(path.join(dir,'backups'));assert.ok(backups.length);const old=JSON.parse(fs.readFileSync(path.join(dir,'backups',backups[0]),'utf8'));assert.equal(old.events[0].title,'第一次保存');}finally{fs.rmSync(dir,{recursive:true,force:true});}});
